### ISSUE TITLE
Make Jailbreak More Stable

### ISSUE THREAD

**Issue by Jefferyat** [TheRealClarity/wtfis#8] opened 2023-12-26 19:55 UTC
there has been NOTHING but issues with this Jailbreak that need to be fixed

Errors like "Cydia Method died unexpectedly which means Cydia is failing to make requests and the Cydia app in the Jailbreak seems very broken, even that happens when you upgrade any outdated cydia packages

On Some ocassions after installing wtfis - Cydia will crash every single time you open it

When running cydia eraser on the jailbroken device to start fresh - it will bootloop your device

Jailbreak is just not very stable, it needs more updates

**Comment by TheRealClarity** [comment] 2023-12-26 20:01
> Errors like "Cydia Method died unexpectedly which means Cydia is failing to make requests and the Cydia app in the Jailbreak seems very broken, even that happens when you upgrade any outdated cydia packages

Nothing I can do. There's no other package manager or bootstrap for iOS 8.

> On Some ocassions after installing wtfis - Cydia will crash every single time you open it

Again, it's not my fault. If you're booted, you're jailbroken and everything's ok with the jailbreak. If something was wrong, you wouldn't boot. If you're able to pinpoint the issue, I'm more than willing to fix it.

> When running cydia eraser on the jailbroken device to start fresh - it will bootloop your device

How so? I've ran Cydia Eraser literally more than 100 times and never once bootlooped. What's the cause? What happens exactly? Is it the root partition that gets full?

> Jailbreak is just not very stable, it needs more updates

???

**Comment by Jefferyat** [comment] 2023-12-26 20:03
is this Jailbreak stable on iOS 8.2??

**Comment by Jefferyat** [comment] 2023-12-26 20:06
are Jailbreak tweaks working with wtfis??

**Comment by Jefferyat** [comment] 2023-12-26 20:07
How can i Jailbreak using wtfis without boot-loops

**Comment by TheRealClarity** [comment] 2023-12-26 20:08
Ok, I'm closing this. If you need support, please ask on the Legacy jailbreak server. If any issue with the jailbreak is found, let me know.

**Closed as completed by TheRealClarity** 2023-12-26 20:08 UTC
