### ISSUE TITLE
Cydia “Method http died unexpectedly”

### ISSUE THREAD

**Issue by Lawin0129** [TheRealClarity/wtfis#7] opened 2023-12-11 06:01 UTC
I'm on an iPhone 5s on iOS 8.2. All of a sudden Cydia is failing to make requests, I have no other way of installing debian files which means I can’t even get Cydia Eraser.
Sideloading Filza also does not work because it only has read permissions when you sideload, not write/delete.

It was working perfectly fine until suddenly all I remember is that Cydia just stopped sending requests entirely and the app seems very broken. I didn’t install or delete anything. iirc, I think I did a complete upgrade of the outdated Cydia packages then restarted my iPhone and this started happening.

I assume the only way I will be able to fix it is with an SSH ramdisk. I’ve tried so many times before on a Linux machine to run an SSH ramdisk on any iPhone and it has never worked for me before. I think MacOS is more compatible with these things but sadly I don’t own any MacOS machine.
![image](https://github.com/TheRealClarity/wtfis/assets/56766256/a09962f1-8856-45a2-91b5-fbee53bd7daf)

**Comment by TheRealClarity** [comment] 2023-12-11 09:10
Did you run erase all contents and settings?

**Comment by Lawin0129** [comment] 2023-12-11 15:14
> Did you run erase all contents and settings?

Nope

**Comment by TheRealClarity** [comment] 2023-12-11 15:18
Very weird, pretty sure you’re jailbroken too, does the wtfis app instantly crash?

**Comment by Lawin0129** [comment] 2023-12-11 15:18
> Very weird, pretty sure you’re jailbroken too, does the wtfis app instantly crash?

Yeah

**Comment by Lawin0129** [comment] 2023-12-11 15:56
> Very weird, pretty sure you’re jailbroken too, does the wtfis app instantly crash?

here's a video of me showing the Cydia app, filza permissions restricted (i think because its sideloaded) and the wtfis app crashing: [IMG_0847.mov](https://cdn.discordapp.com/attachments/927739901540188200/1183798762712334346/IMG_0847.mov)

**Comment by Lawin0129** [comment] 2023-12-11 16:03
I guess the only way to fix this is with an SSH ramdisk right?

**Comment by TheRealClarity** [comment] 2023-12-11 16:24
> I guess the only way to fix this is with an SSH ramdisk right?

Yes. I have some development code that would spawn a dropbear shell that I might release _some day_ but it isn’t planned for now.
I’ll be closing this since it’s not a problem directly caused by wtfis. 
You can ask for help in the legacy server and I’ll chime in if needed.

**Closed as completed by TheRealClarity** 2023-12-11 16:24 UTC

**Comment by Lawin0129** [comment] 2023-12-11 16:26
Alright, thank you
